# PCA exercise

In [187]:
import numpy as np

This creates a dataset of 200 data points. 

In [188]:
np.random.seed(1976)
A = np.random.random(size=(7,7))
cov = np.dot(A.T,A)
X = np.random.multivariate_normal(np.zeros(7),cov, size=200)
av = np.average(X,axis=0)
std = np.std(X, axis=0)

Xnorm = (X-av)/std 

## Task 1

Use PCA to determine how many dimensions you need to keep to maintain 95% of the variance. 

Determine the transformation that projects the dataset `Xnorm` onto the space of reduced dimension that keeps 95% of the variance. Verify explicitely that the variance of the reduced data is what you expect.  

In [209]:
# Determine the fractions of the variance that the first i principle components maintain.
# Return your result as an array of length 7 where entry i represents the fraction of
# the explained variance maintained by the first i principle components. 
from sklearn.decomposition import PCA
def calculate_fractions(X):
    # YOUR CODE HERE
#     n_samples, n_features = X.shape
#     sigma = np.dot(np.transpose(X),X)
    
#     eig_val, eig_vec = np.linalg.eig(sigma)
    
#     fraction = np.cumsum(eig_val) / np.sum(eig_val)
#     eig_pairs = [(np.abs(eig_val[i]), eig_vec[:,i]) for i in range(n_features)]
    
#     eig_pairs.sort(reverse=True)
    
#     feature=np.array([ele[1] for ele in eig_pairs[:7]])
    
#     data=np.dot(X,np.transpose(feature))
    
#     return fraction
    pca = PCA(n_components = 7)
    pca.fit(X)
    fractions = pca.explained_variance_ratio_
    for i in range(1, len(fractions)):
        fractions[i] += fractions[i - 1]
    print(fractions)
    return(fractions)

In [210]:
assert np.isclose(calculate_fractions(Xnorm),np.array([0.82887306, 0.90096354, 0.96292231, 0.98337372, 0.99726923, 0.99913066, 1. ])).all()

[0.82887306 0.90096354 0.96292231 0.98337372 0.99726923 0.99913066
 1.        ]


In [194]:
# Determine the transformation that projects the dataset Xnorm onto the space of reduced dimension 
# that keeps 95% of the variance

# Name the reduced dataset 'reduced'. We will use a dataset with this name as an input in one of the test cells.
pca = PCA(n_components = 0.95)
reduced = pca.fit_transform(Xnorm)
print(reduced[:3])

[[-0.22672849 -0.80162514  0.29934808]
 [ 1.45611279 -0.41283112 -0.03976126]
 [ 1.76252416 -1.40875441 -1.25272327]]


In [202]:
# Verify explicitely that the variance of the reduced data is what you expect. 
# Calculate the variance of the reduced data set

# your function should return the variance of reduced data set
def calculate_variance(reduced):
    return np.trace(np.dot(reduced.T, reduced)/ reduced.shape[0])

calculate_variance(reduced)

6.740456198634824

In [200]:
assert np.isclose(calculate_variance(reduced),6.740456198634824)

Compare the variance to your results from `calculate_fractions`. 


In [ ]:
# YOUR CODE HERE